### ISSUE TITLE
Crystal 1.2 issue

### ISSUE THREAD

**Issue by mamantoha** [Papierkorb/qt5.cr#48]
Hi!

Something was changed between Crystal 1.1.1 and 1.2.0 (currently in development).

Can't run any sample.

Output:

```
Showing last frame. Use --error-trace for full trace.

In src/qt5/binding/binding_.cr:49833:3

 49833 | class GraphicsSimpleTextItem < AbstractGraphicsShapeItem
         ^
Error: abstract `def Qt::AbstractGraphicsShapeItem#paint(painter : Painter, option : StyleOptionGraphicsItem, widget : Widget | ::Nil = nil)` must be implemented by Qt::GraphicsSimpleTextItem
```

Can be "fixed" by commenting line `src/qt5/binding/binding_.cr:47974`

```
abstract def paint(painter : Painter, option : StyleOptionGraphicsItem, widget : Widget? = nil) : Void
```

**Comment by f-fr** [comment]
I've looked a little bit in this issue. AFAICT the problem is as follows:

1. C++ pointer arguments are usually deferred to be non-nilable, i.e. an argument `foo(Object* obj)` becomes `foo(obj : Object)` in Crystal.
2. There is one exception: if the argument has a default value 0 (or `nullptr`) is will be nilable, i.e. an argument `foo(Object* obj = 0)` becomes `foo(obj : Object?)` (well actually it becomes `foo(obj : Object? = nil)` but that's not the problem).
3. In C++ it is perfectly possible to define some method in a base class with an argument *with* default value and redefine it in a subclass *without* default value.

The point is that `Object` and `Object?` a different types in Crystal. Now if some base class A defines a (virtual) method with a pointer argument with default value and a subclass B that overrides this method but without the default value, then the generated Crystal code will be roughly
```
abstract class A
  abstract def foo(obj : Object?)
end

class B < A
  def foo(obj : Object) .... end
end
```
and the `foo` method in B does *not* override `foo` from A. This is what happens in this example because in Qt the `paint` method in QGraphicsItem is defined `void paint(..., QWidget* widget = 0)` and overwritten in QGraphicsSimpleTextItem with `void paint(..., QWidget* widget)`. This might not be a good style but it is perfectly valid and we have to live with it.

The proper solution would probably be to write another "processor" for bindgen (it's actually a bindgen issue, and not specific to qt5.cr) that walks through all virtual methods of all classes and looks if they redefine some method in a superclass. If this is the case then the "nilability" from the defining superclass should be taken.

**Comment by f-fr** [comment]
I submitted a PR to bindgen that should solve this problem.

**Comment by mamantoha** [comment]
@f-fr awesome!
